# Site settings
title: Hi, I'm Kanish.
description: Kanish Chugh' professional portfolio site
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Kanish Chugh
user_description: I am Kanish Chugh, a recent graduate with a Bachelors degree,
     aspiring to become a Data Scientist. My passion for the field of Data Science extends to exploring the realms of Machine Learning,
      IoT applications, and Robotics. I am deeply enthusiastic about collaborating on open source projects on Github, where I aim to contribute and drive innovation in these domains. With a strong foundation and a curious mindset, 
      I am eager to leverage data-driven insights to tackle complex challenges and make a positive impact in the world of data science. 
      If you are interested in working together or having a discussion, please don't hesitate to get in touch with me. I'm open to connecting and exploring potential opportunities.

user_title: Mr.
user_job_title: Data Scientist
email: kanishchugh2001@gmail.com
twitter_username: kanish_chugh
github_username:  kanishchugh

exclude: ['package.json', 'src' , 'node_modules']
